spring:
  application:
    name: ws-qsalud
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 5000

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO